// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl) returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Creates a new key, stores it, then returns key parameters and attributes to the client.
    #
    # + keyName - The name for the new key. The system will generate the version name for the new key
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters to create a key 
    # + return - A key bundle containing the result of the create key request 
    remote isolated function createKey(string keyName, KeyCreateParameters payload, map<string|string[]> headers = {}, *CreateKeyQueries queries) returns KeyBundle|error {
        string resourcePath = string `/keys/${getEncodedUri(keyName)}/create`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Imports an externally created key, stores it, and returns key parameters and attributes to the client.
    #
    # + keyName - Name for the imported key
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters to import a key 
    # + return - Imported key bundle to the vault 
    remote isolated function importKey(string keyName, KeyImportParameters payload, map<string|string[]> headers = {}, *ImportKeyQueries queries) returns KeyBundle|error {
        string resourcePath = string `/keys/${getEncodedUri(keyName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Deletes a key of any type from storage in Azure Key Vault.
    #
    # + keyName - The name of the key to delete
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The public part of the deleted key and deletion information on when the key will be purged 
    remote isolated function deleteKey(string keyName, map<string|string[]> headers = {}, *DeleteKeyQueries queries) returns DeletedKeyBundle|error {
        string resourcePath = string `/keys/${getEncodedUri(keyName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Gets the public part of a stored key.
    #
    # + keyName - The name of the key to get
    # + keyVersion - Adding the version parameter retrieves a specific version of a key
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A key bundle containing the key and its attributes 
    remote isolated function getKey(string keyName, string keyVersion, map<string|string[]> headers = {}, *GetKeyQueries queries) returns KeyBundle|error {
        string resourcePath = string `/keys/${getEncodedUri(keyName)}/${getEncodedUri(keyVersion)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # The update key operation changes specified attributes of a stored key and can be applied to any key type and key version stored in Azure Key Vault.
    #
    # + keyName - The name of key to update
    # + keyVersion - The version of the key to update
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters of the key to update 
    # + return - The updated key 
    remote isolated function updateKey(string keyName, string keyVersion, KeyUpdateParameters payload, map<string|string[]> headers = {}, *UpdateKeyQueries queries) returns KeyBundle|error {
        string resourcePath = string `/keys/${getEncodedUri(keyName)}/${getEncodedUri(keyVersion)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Retrieves a list of individual key versions with the same key name.
    #
    # + keyName - The name of the key
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A response message containing a list of keys along with a link to the next page of keys 
    remote isolated function listKeyVersions(string keyName, map<string|string[]> headers = {}, *ListKeyVersionsQueries queries) returns KeyListResult|error {
        string resourcePath = string `/keys/${getEncodedUri(keyName)}/versions`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # List keys in the specified vault.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A response message containing a list of keys in the vault along with a link to the next page of keys 
    remote isolated function listKeys(map<string|string[]> headers = {}, *ListKeysQueries queries) returns KeyListResult|error {
        string resourcePath = string `/keys`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Requests that a backup of the specified key be downloaded to the client.
    #
    # + keyName - The name of the key
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The backup blob containing the backed up key 
    remote isolated function backupKey(string keyName, map<string|string[]> headers = {}, *BackupKeyQueries queries) returns BackupKeyResult|error {
        string resourcePath = string `/keys/${getEncodedUri(keyName)}/backup`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Restores a backed up key to a vault.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters to restore the key 
    # + return - Restored key bundle in the vault 
    remote isolated function restoreKey(KeyRestoreParameters payload, map<string|string[]> headers = {}, *RestoreKeyQueries queries) returns KeyBundle|error {
        string resourcePath = string `/keys/restore`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Encrypts an arbitrary sequence of bytes using an encryption key that is stored in a key vault.
    #
    # + keyName - The name of the key
    # + keyVersion - The version of the key
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters for the encryption operation 
    # + return - The encryption result 
    remote isolated function encrypt(string keyName, string keyVersion, KeyOperationsParameters payload, map<string|string[]> headers = {}, *EncryptQueries queries) returns KeyOperationResult|error {
        string resourcePath = string `/keys/${getEncodedUri(keyName)}/${getEncodedUri(keyVersion)}/encrypt`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Decrypts a single block of encrypted data.
    #
    # + keyName - The name of the key
    # + keyVersion - The version of the key
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters for the decryption operation 
    # + return - The decryption result 
    remote isolated function decrypt(string keyName, string keyVersion, KeyOperationsParameters payload, map<string|string[]> headers = {}, *DecryptQueries queries) returns KeyOperationResult|error {
        string resourcePath = string `/keys/${getEncodedUri(keyName)}/${getEncodedUri(keyVersion)}/decrypt`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Creates a signature from a digest using the specified key.
    #
    # + keyName - The name of the key
    # + keyVersion - The version of the key
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters for the signing operation 
    # + return - The signature value 
    remote isolated function sign(string keyName, string keyVersion, KeySignParameters payload, map<string|string[]> headers = {}, *SignQueries queries) returns KeyOperationResult|error {
        string resourcePath = string `/keys/${getEncodedUri(keyName)}/${getEncodedUri(keyVersion)}/sign`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Verifies a signature using a specified key.
    #
    # + keyName - The name of the key
    # + keyVersion - The version of the key
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters for verify operations 
    # + return - The verification result 
    remote isolated function verify(string keyName, string keyVersion, KeyVerifyParameters payload, map<string|string[]> headers = {}, *VerifyQueries queries) returns KeyVerifyResult|error {
        string resourcePath = string `/keys/${getEncodedUri(keyName)}/${getEncodedUri(keyVersion)}/verify`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Wraps a symmetric key using a specified key.
    #
    # + keyName - The name of the key
    # + keyVersion - The version of the key
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters for wrap operation 
    # + return - The wrapped symmetric key 
    remote isolated function wrapKey(string keyName, string keyVersion, KeyOperationsParameters payload, map<string|string[]> headers = {}, *WrapKeyQueries queries) returns KeyOperationResult|error {
        string resourcePath = string `/keys/${getEncodedUri(keyName)}/${getEncodedUri(keyVersion)}/wrapkey`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Unwraps a symmetric key using the specified key that was initially used for wrapping that key.
    #
    # + keyName - The name of the key
    # + keyVersion - The version of the key
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters for the key operation 
    # + return - The unwrapped symmetric key 
    remote isolated function unwrapKey(string keyName, string keyVersion, KeyOperationsParameters payload, map<string|string[]> headers = {}, *UnwrapKeyQueries queries) returns KeyOperationResult|error {
        string resourcePath = string `/keys/${getEncodedUri(keyName)}/${getEncodedUri(keyVersion)}/unwrapkey`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Lists the deleted keys in the specified vault.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A response message containing a list of deleted keys in the vault along with a link to the next page of deleted keys 
    remote isolated function listDeletedKeys(map<string|string[]> headers = {}, *ListDeletedKeysQueries queries) returns DeletedKeyListResult|error {
        string resourcePath = string `/deletedkeys`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Gets the public part of a deleted key.
    #
    # + keyName - The name of the key
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A DeletedKeyBundle consisting of a WebKey plus its Attributes and deletion information 
    remote isolated function getDeletedKey(string keyName, map<string|string[]> headers = {}, *GetDeletedKeyQueries queries) returns DeletedKeyBundle|error {
        string resourcePath = string `/deletedkeys/${getEncodedUri(keyName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Permanently deletes the specified key.
    #
    # + keyName - The name of the key
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - No content, signaling that the key was permanently purged 
    remote isolated function purgeDeletedKey(string keyName, map<string|string[]> headers = {}, *PurgeDeletedKeyQueries queries) returns error? {
        string resourcePath = string `/deletedkeys/${getEncodedUri(keyName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Recovers the deleted key to its latest version.
    #
    # + keyName - The name of the deleted key
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A Key bundle of the original key and its attributes 
    remote isolated function recoverDeletedKey(string keyName, map<string|string[]> headers = {}, *RecoverDeletedKeyQueries queries) returns KeyBundle|error {
        string resourcePath = string `/deletedkeys/${getEncodedUri(keyName)}/recover`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Sets a secret in a specified key vault.
    #
    # + secretName - The name of the secret
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters for setting the secret 
    # + return - A secret bundle containing the result of the set secret request 
    remote isolated function setSecret(string secretName, SecretSetParameters payload, map<string|string[]> headers = {}, *SetSecretQueries queries) returns SecretBundle|error {
        string resourcePath = string `/secrets/${getEncodedUri(secretName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Deletes a secret from a specified key vault.
    #
    # + secretName - The name of the secret
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The deleted secret and information on when the secret will be deleted, and how to recover the deleted secret 
    remote isolated function deleteSecret(string secretName, map<string|string[]> headers = {}, *DeleteSecretQueries queries) returns DeletedSecretBundle|error {
        string resourcePath = string `/secrets/${getEncodedUri(secretName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Get a specified secret from a given key vault.
    #
    # + secretName - The name of the secret
    # + secretVersion - The version of the secret
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved secret 
    remote isolated function getSecret(string secretName, string secretVersion, map<string|string[]> headers = {}, *GetSecretQueries queries) returns SecretBundle|error {
        string resourcePath = string `/secrets/${getEncodedUri(secretName)}/${getEncodedUri(secretVersion)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Updates the attributes associated with a specified secret in a given key vault.
    #
    # + secretName - The name of the secret
    # + secretVersion - The version of the secret
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters for update secret operation 
    # + return - The updated secret 
    remote isolated function updateSecret(string secretName, string secretVersion, SecretUpdateParameters payload, map<string|string[]> headers = {}, *UpdateSecretQueries queries) returns SecretBundle|error {
        string resourcePath = string `/secrets/${getEncodedUri(secretName)}/${getEncodedUri(secretVersion)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # List secrets in a specified key vault.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A response message containing a list of secrets in the vault along with a link to the next page of secrets 
    remote isolated function listSecrets(map<string|string[]> headers = {}, *ListSecretsQueries queries) returns SecretListResult|error {
        string resourcePath = string `/secrets`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # List all versions of the specified secret.
    #
    # + secretName - The name of the secret
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A response message containing a list of secrets along with a link to the next page of secrets 
    remote isolated function listSecretVersions(string secretName, map<string|string[]> headers = {}, *ListSecretVersionsQueries queries) returns SecretListResult|error {
        string resourcePath = string `/secrets/${getEncodedUri(secretName)}/versions`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Lists deleted secrets for the specified vault.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A response message containing a list of deleted secrets in the vault, along with a link to the next page of deleted secrets 
    remote isolated function listDeletedSecrets(map<string|string[]> headers = {}, *ListDeletedSecretsQueries queries) returns DeletedSecretListResult|error {
        string resourcePath = string `/deletedsecrets`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Gets the specified deleted secret.
    #
    # + secretName - The name of the secret
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A secret bundle of the secret and its attributes 
    remote isolated function getDeletedSecret(string secretName, map<string|string[]> headers = {}, *GetDeletedSecretQueries queries) returns DeletedSecretBundle|error {
        string resourcePath = string `/deletedsecrets/${getEncodedUri(secretName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Permanently deletes the specified secret.
    #
    # + secretName - The name of the secret
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - No content signaling that the secret was purged forever 
    remote isolated function purgeDeletedSecret(string secretName, map<string|string[]> headers = {}, *PurgeDeletedSecretQueries queries) returns error? {
        string resourcePath = string `/deletedsecrets/${getEncodedUri(secretName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Recovers the deleted secret to the latest version.
    #
    # + secretName - The name of the deleted secret
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A Secret bundle of the original secret and its attributes 
    remote isolated function recoverDeletedSecret(string secretName, map<string|string[]> headers = {}, *RecoverDeletedSecretQueries queries) returns SecretBundle|error {
        string resourcePath = string `/deletedsecrets/${getEncodedUri(secretName)}/recover`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Backs up the specified secret.
    #
    # + secretName - The name of the secret
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The backup blob containing the backed up secret 
    remote isolated function backupSecret(string secretName, map<string|string[]> headers = {}, *BackupSecretQueries queries) returns BackupSecretResult|error {
        string resourcePath = string `/secrets/${getEncodedUri(secretName)}/backup`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Restores a backed up secret to a vault.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters to restore the secret 
    # + return - Restored secret bundle in the vault 
    remote isolated function restoreSecret(SecretRestoreParameters payload, map<string|string[]> headers = {}, *RestoreSecretQueries queries) returns SecretBundle|error {
        string resourcePath = string `/secrets/restore`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # List certificates in a specified key vault
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A response message containing a list of certificates along with a link to the next page of certificates 
    remote isolated function listCertificates(map<string|string[]> headers = {}, *ListCertificatesQueries queries) returns CertificateListResult|error {
        string resourcePath = string `/certificates`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Deletes a certificate from a specified key vault.
    #
    # + certificateName - The name of the certificate
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The deleted certificate 
    remote isolated function deleteCertificate(string certificateName, map<string|string[]> headers = {}, *DeleteCertificateQueries queries) returns DeletedCertificateBundle|error {
        string resourcePath = string `/certificates/${getEncodedUri(certificateName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Lists the certificate contacts for a specified key vault.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The contacts for the key vault certificate 
    remote isolated function getCertificateContacts(map<string|string[]> headers = {}, *GetCertificateContactsQueries queries) returns Contacts|error {
        string resourcePath = string `/certificates/contacts`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Sets the certificate contacts for the specified key vault.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The contacts for the key vault certificate 
    # + return - The contacts for the key vault certificate 
    remote isolated function setCertificateContacts(Contacts payload, map<string|string[]> headers = {}, *SetCertificateContactsQueries queries) returns Contacts|error {
        string resourcePath = string `/certificates/contacts`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Deletes the certificate contacts for a specified key vault.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The contacts for the key vault certificate 
    remote isolated function deleteCertificateContacts(map<string|string[]> headers = {}, *DeleteCertificateContactsQueries queries) returns Contacts|error {
        string resourcePath = string `/certificates/contacts`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # List certificate issuers for a specified key vault.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A response message containing a list of certificate issuers in a key vault along with a link to the next page of certificate issuers 
    remote isolated function listCertificateIssuers(map<string|string[]> headers = {}, *ListCertificateIssuersQueries queries) returns CertificateIssuerListResult|error {
        string resourcePath = string `/certificates/issuers`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Lists the specified certificate issuer.
    #
    # + issuerName - The name of the issuer
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The issuer for the key vault certificate 
    remote isolated function getCertificateIssuer(string issuerName, map<string|string[]> headers = {}, *GetCertificateIssuerQueries queries) returns IssuerBundle|error {
        string resourcePath = string `/certificates/issuers/${getEncodedUri(issuerName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Sets the specified certificate issuer.
    #
    # + issuerName - The name of the issuer
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Certificate issuer set parameter 
    # + return - The issuer for the key vault certificate 
    remote isolated function setCertificateIssuer(string issuerName, CertificateIssuerSetParameters payload, map<string|string[]> headers = {}, *SetCertificateIssuerQueries queries) returns IssuerBundle|error {
        string resourcePath = string `/certificates/issuers/${getEncodedUri(issuerName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Deletes the specified certificate issuer.
    #
    # + issuerName - The name of the issuer
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The issuer for the key vault certificate 
    remote isolated function deleteCertificateIssuer(string issuerName, map<string|string[]> headers = {}, *DeleteCertificateIssuerQueries queries) returns IssuerBundle|error {
        string resourcePath = string `/certificates/issuers/${getEncodedUri(issuerName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Updates the specified certificate issuer.
    #
    # + issuerName - The name of the issuer
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Certificate issuer update parameter 
    # + return - The issuer for the key vault certificate 
    remote isolated function updateCertificateIssuer(string issuerName, CertificateIssuerUpdateParameters payload, map<string|string[]> headers = {}, *UpdateCertificateIssuerQueries queries) returns IssuerBundle|error {
        string resourcePath = string `/certificates/issuers/${getEncodedUri(issuerName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Creates a new certificate.
    #
    # + certificateName - The name of the certificate
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters to create a certificate 
    # + return - Created certificate bundle 
    remote isolated function createCertificate(string certificateName, CertificateCreateParameters payload, map<string|string[]> headers = {}, *CreateCertificateQueries queries) returns CertificateOperation|error {
        string resourcePath = string `/certificates/${getEncodedUri(certificateName)}/create`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Imports a certificate into a specified key vault.
    #
    # + certificateName - The name of the certificate
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters to import the certificate 
    # + return - Imported certificate bundle to the vault 
    remote isolated function importCertificate(string certificateName, CertificateImportParameters payload, map<string|string[]> headers = {}, *ImportCertificateQueries queries) returns CertificateBundle|error {
        string resourcePath = string `/certificates/${getEncodedUri(certificateName)}/import`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # List the versions of a certificate.
    #
    # + certificateName - The name of the certificate
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A response message containing a list of certificates in the key vault along with a link to the next page of keys 
    remote isolated function listCertificateVersions(string certificateName, map<string|string[]> headers = {}, *ListCertificateVersionsQueries queries) returns CertificateListResult|error {
        string resourcePath = string `/certificates/${getEncodedUri(certificateName)}/versions`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Lists the policy for a certificate.
    #
    # + certificateName - The name of the certificate in a given key vault
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The certificate policy 
    remote isolated function getCertificatePolicy(string certificateName, map<string|string[]> headers = {}, *GetCertificatePolicyQueries queries) returns CertificatePolicy|error {
        string resourcePath = string `/certificates/${getEncodedUri(certificateName)}/policy`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Updates the policy for a certificate.
    #
    # + certificateName - The name of the certificate in the given vault
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The policy for the certificate 
    # + return - The certificate policy 
    remote isolated function updateCertificatePolicy(string certificateName, CertificatePolicy payload, map<string|string[]> headers = {}, *UpdateCertificatePolicyQueries queries) returns CertificatePolicy|error {
        string resourcePath = string `/certificates/${getEncodedUri(certificateName)}/policy`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Gets information about a certificate.
    #
    # + certificateName - The name of the certificate in the given vault
    # + certificateVersion - The version of the certificate
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved certificate 
    remote isolated function getCertificate(string certificateName, string certificateVersion, map<string|string[]> headers = {}, *GetCertificateQueries queries) returns CertificateBundle|error {
        string resourcePath = string `/certificates/${getEncodedUri(certificateName)}/${getEncodedUri(certificateVersion)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Updates the specified attributes associated with the given certificate.
    #
    # + certificateName - The name of the certificate in the given key vault
    # + certificateVersion - The version of the certificate
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters for certificate update 
    # + return - The updated certificate 
    remote isolated function updateCertificate(string certificateName, string certificateVersion, CertificateUpdateParameters payload, map<string|string[]> headers = {}, *UpdateCertificateQueries queries) returns CertificateBundle|error {
        string resourcePath = string `/certificates/${getEncodedUri(certificateName)}/${getEncodedUri(certificateVersion)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Gets the creation operation of a certificate.
    #
    # + certificateName - The name of the certificate
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The certificate operation response 
    remote isolated function getCertificateOperation(string certificateName, map<string|string[]> headers = {}, *GetCertificateOperationQueries queries) returns CertificateOperation|error {
        string resourcePath = string `/certificates/${getEncodedUri(certificateName)}/pending`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Deletes the creation operation for a specific certificate.
    #
    # + certificateName - The name of the certificate
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A message containing the certificate operation response 
    remote isolated function deleteCertificateOperation(string certificateName, map<string|string[]> headers = {}, *DeleteCertificateOperationQueries queries) returns CertificateOperation|error {
        string resourcePath = string `/certificates/${getEncodedUri(certificateName)}/pending`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Updates a certificate operation.
    #
    # + certificateName - The name of the certificate
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The certificate operation response 
    # + return - A message containing the certificate operation response 
    remote isolated function updateCertificateOperation(string certificateName, CertificateOperationUpdateParameter payload, map<string|string[]> headers = {}, *UpdateCertificateOperationQueries queries) returns CertificateOperation|error {
        string resourcePath = string `/certificates/${getEncodedUri(certificateName)}/pending`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Merges a certificate or a certificate chain with a key pair existing on the server.
    #
    # + certificateName - The name of the certificate
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters to merge certificate 
    # + return - Merged certificate bundle to the vault 
    remote isolated function mergeCertificate(string certificateName, CertificateMergeParameters payload, map<string|string[]> headers = {}, *MergeCertificateQueries queries) returns CertificateBundle|error {
        string resourcePath = string `/certificates/${getEncodedUri(certificateName)}/pending/merge`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Backs up the specified certificate.
    #
    # + certificateName - The name of the certificate
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The backup blob containing the backed up certificate 
    remote isolated function backupCertificate(string certificateName, map<string|string[]> headers = {}, *BackupCertificateQueries queries) returns BackupCertificateResult|error {
        string resourcePath = string `/certificates/${getEncodedUri(certificateName)}/backup`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Restores a backed up certificate to a vault.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters to restore the certificate 
    # + return - Restored certificate bundle in the vault 
    remote isolated function restoreCertificate(CertificateRestoreParameters payload, map<string|string[]> headers = {}, *RestoreCertificateQueries queries) returns CertificateBundle|error {
        string resourcePath = string `/certificates/restore`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Lists the deleted certificates in the specified vault currently available for recovery.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A response message containing a list of deleted certificates in the vault along with a link to the next page of deleted certificates 
    remote isolated function listDeletedCertificates(map<string|string[]> headers = {}, *ListDeletedCertificatesQueries queries) returns DeletedCertificateListResult|error {
        string resourcePath = string `/deletedcertificates`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Retrieves information about the specified deleted certificate.
    #
    # + certificateName - The name of the certificate
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A Certificate bundle of the certificate and its attributes 
    remote isolated function getDeletedCertificate(string certificateName, map<string|string[]> headers = {}, *GetDeletedCertificateQueries queries) returns DeletedCertificateBundle|error {
        string resourcePath = string `/deletedcertificates/${getEncodedUri(certificateName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Permanently deletes the specified deleted certificate.
    #
    # + certificateName - The name of the certificate
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - No content signaling that the certificate was purged forever 
    remote isolated function purgeDeletedCertificate(string certificateName, map<string|string[]> headers = {}, *PurgeDeletedCertificateQueries queries) returns error? {
        string resourcePath = string `/deletedcertificates/${getEncodedUri(certificateName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Recovers the deleted certificate back to its current version under /certificates.
    #
    # + certificateName - The name of the deleted certificate
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A Certificate bundle of the original certificate and its attributes 
    remote isolated function recoverDeletedCertificate(string certificateName, map<string|string[]> headers = {}, *RecoverDeletedCertificateQueries queries) returns CertificateBundle|error {
        string resourcePath = string `/deletedcertificates/${getEncodedUri(certificateName)}/recover`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # List storage accounts managed by the specified key vault.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A response message containing a list of storage accounts along with a link to the next page of storage accounts 
    remote isolated function listStorageAccounts(map<string|string[]> headers = {}, *ListStorageAccountsQueries queries) returns StorageListResult|error {
        string resourcePath = string `/storage`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Lists deleted storage accounts for the specified vault.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A response message containing a list of deleted storage accounts in the vault, along with a link to the next page of deleted storage accounts 
    remote isolated function listDeletedStorageAccounts(map<string|string[]> headers = {}, *ListDeletedStorageAccountsQueries queries) returns DeletedStorageListResult|error {
        string resourcePath = string `/deletedstorage`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Gets the specified deleted storage account.
    #
    # + storageAccountName - The name of the storage account
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The deleted storage account and information on when it will be purged, and how to recover the deleted storage account 
    remote isolated function getDeletedStorageAccount(string storageAccountName, map<string|string[]> headers = {}, *GetDeletedStorageAccountQueries queries) returns DeletedStorageBundle|error {
        string resourcePath = string `/deletedstorage/${getEncodedUri(storageAccountName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Permanently deletes the specified storage account.
    #
    # + storageAccountName - The name of the storage account
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - No content signaling that the storage account was purged forever 
    remote isolated function purgeDeletedStorageAccount(string storageAccountName, map<string|string[]> headers = {}, *PurgeDeletedStorageAccountQueries queries) returns error? {
        string resourcePath = string `/deletedstorage/${getEncodedUri(storageAccountName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Recovers the deleted storage account.
    #
    # + storageAccountName - The name of the storage account
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A storage bundle of the original storage account and its attributes 
    remote isolated function recoverDeletedStorageAccount(string storageAccountName, map<string|string[]> headers = {}, *RecoverDeletedStorageAccountQueries queries) returns StorageBundle|error {
        string resourcePath = string `/deletedstorage/${getEncodedUri(storageAccountName)}/recover`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Backs up the specified storage account.
    #
    # + storageAccountName - The name of the storage account
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The backup blob containing the backed up storage account 
    remote isolated function backupStorageAccount(string storageAccountName, map<string|string[]> headers = {}, *BackupStorageAccountQueries queries) returns BackupStorageResult|error {
        string resourcePath = string `/storage/${getEncodedUri(storageAccountName)}/backup`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Restores a backed up storage account to a vault.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters to restore the storage account 
    # + return - Restored storage account bundle in the vault 
    remote isolated function restoreStorageAccount(StorageRestoreParameters payload, map<string|string[]> headers = {}, *RestoreStorageAccountQueries queries) returns StorageBundle|error {
        string resourcePath = string `/storage/restore`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Gets information about a specified storage account.
    #
    # + storageAccountName - The name of the storage account
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved storage account 
    remote isolated function getStorageAccount(string storageAccountName, map<string|string[]> headers = {}, *GetStorageAccountQueries queries) returns StorageBundle|error {
        string resourcePath = string `/storage/${getEncodedUri(storageAccountName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Creates or updates a new storage account.
    #
    # + storageAccountName - The name of the storage account
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters to create a storage account 
    # + return - The created storage account 
    remote isolated function setStorageAccount(string storageAccountName, StorageAccountCreateParameters payload, map<string|string[]> headers = {}, *SetStorageAccountQueries queries) returns StorageBundle|error {
        string resourcePath = string `/storage/${getEncodedUri(storageAccountName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Deletes a storage account.
    #
    # + storageAccountName - The name of the storage account
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The deleted storage account and information on when the storage account will be deleted, and how to recover the deleted storage account 
    remote isolated function deleteStorageAccount(string storageAccountName, map<string|string[]> headers = {}, *DeleteStorageAccountQueries queries) returns DeletedStorageBundle|error {
        string resourcePath = string `/storage/${getEncodedUri(storageAccountName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Updates the specified attributes associated with the given storage account.
    #
    # + storageAccountName - The name of the storage account
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters to update a storage account 
    # + return - The updated storage account 
    remote isolated function updateStorageAccount(string storageAccountName, StorageAccountUpdateParameters payload, map<string|string[]> headers = {}, *UpdateStorageAccountQueries queries) returns StorageBundle|error {
        string resourcePath = string `/storage/${getEncodedUri(storageAccountName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Regenerates the specified key value for the given storage account.
    #
    # + storageAccountName - The name of the storage account
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters to regenerate storage account key 
    # + return - The updated storage account 
    remote isolated function regenerateStorageAccountKey(string storageAccountName, StorageAccountRegenerateKeyParameters payload, map<string|string[]> headers = {}, *RegenerateStorageAccountKeyQueries queries) returns StorageBundle|error {
        string resourcePath = string `/storage/${getEncodedUri(storageAccountName)}/regeneratekey`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # List storage SAS definitions for the given storage account.
    #
    # + storageAccountName - The name of the storage account
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A response message containing a list of SAS definitions along with a link to the next page of SAS definitions 
    remote isolated function listSasDefinitions(string storageAccountName, map<string|string[]> headers = {}, *ListSasDefinitionsQueries queries) returns SasDefinitionListResult|error {
        string resourcePath = string `/storage/${getEncodedUri(storageAccountName)}/sas`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Lists deleted SAS definitions for the specified vault and storage account.
    #
    # + storageAccountName - The name of the storage account
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A response message containing a list of deleted SAS definitions for the storage account, along with a link to the next page of deleted SAS definitions 
    remote isolated function listDeletedSasDefinitions(string storageAccountName, map<string|string[]> headers = {}, *ListDeletedSasDefinitionsQueries queries) returns DeletedSasDefinitionListResult|error {
        string resourcePath = string `/deletedstorage/${getEncodedUri(storageAccountName)}/sas`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Gets the specified deleted sas definition.
    #
    # + storageAccountName - The name of the storage account
    # + sasDefinitionName - The name of the SAS definition
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The deleted SAS definition and information on when the it will be purged, and how to recover the deleted SAS definition 
    remote isolated function getDeletedSasDefinition(string storageAccountName, string sasDefinitionName, map<string|string[]> headers = {}, *GetDeletedSasDefinitionQueries queries) returns DeletedSasDefinitionBundle|error {
        string resourcePath = string `/deletedstorage/${getEncodedUri(storageAccountName)}/sas/${getEncodedUri(sasDefinitionName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Recovers the deleted SAS definition.
    #
    # + storageAccountName - The name of the storage account
    # + sasDefinitionName - The name of the SAS definition
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A SAS definition bundle of the original SAS definition and its attributes 
    remote isolated function recoverDeletedSasDefinition(string storageAccountName, string sasDefinitionName, map<string|string[]> headers = {}, *RecoverDeletedSasDefinitionQueries queries) returns SasDefinitionBundle|error {
        string resourcePath = string `/deletedstorage/${getEncodedUri(storageAccountName)}/sas/${getEncodedUri(sasDefinitionName)}/recover`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Gets information about a SAS definition for the specified storage account.
    #
    # + storageAccountName - The name of the storage account
    # + sasDefinitionName - The name of the SAS definition
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved SAS definition 
    remote isolated function getSasDefinition(string storageAccountName, string sasDefinitionName, map<string|string[]> headers = {}, *GetSasDefinitionQueries queries) returns SasDefinitionBundle|error {
        string resourcePath = string `/storage/${getEncodedUri(storageAccountName)}/sas/${getEncodedUri(sasDefinitionName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Creates or updates a new SAS definition for the specified storage account.
    #
    # + storageAccountName - The name of the storage account
    # + sasDefinitionName - The name of the SAS definition
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters to create a SAS definition 
    # + return - The created SAS definition 
    remote isolated function setSasDefinition(string storageAccountName, string sasDefinitionName, SasDefinitionCreateParameters payload, map<string|string[]> headers = {}, *SetSasDefinitionQueries queries) returns SasDefinitionBundle|error {
        string resourcePath = string `/storage/${getEncodedUri(storageAccountName)}/sas/${getEncodedUri(sasDefinitionName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Deletes a SAS definition from a specified storage account.
    #
    # + storageAccountName - The name of the storage account
    # + sasDefinitionName - The name of the SAS definition
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The deleted SAS definition and information on when the SAS definition will be deleted, and how to recover the deleted SAS definition 
    remote isolated function deleteSasDefinition(string storageAccountName, string sasDefinitionName, map<string|string[]> headers = {}, *DeleteSasDefinitionQueries queries) returns DeletedSasDefinitionBundle|error {
        string resourcePath = string `/storage/${getEncodedUri(storageAccountName)}/sas/${getEncodedUri(sasDefinitionName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Updates the specified attributes associated with the given SAS definition.
    #
    # + storageAccountName - The name of the storage account
    # + sasDefinitionName - The name of the SAS definition
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The parameters to update a SAS definition 
    # + return - The updated SAS definition 
    remote isolated function updateSasDefinition(string storageAccountName, string sasDefinitionName, SasDefinitionUpdateParameters payload, map<string|string[]> headers = {}, *UpdateSasDefinitionQueries queries) returns SasDefinitionBundle|error {
        string resourcePath = string `/storage/${getEncodedUri(storageAccountName)}/sas/${getEncodedUri(sasDefinitionName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }
}
