// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/constraint;
import ballerina/data.jsondata;
import ballerina/http;

# Represents the Queries record for the operation: listKeys
public type ListKeysQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
    # Specifies the maximum number of results to return in a page. Setting maxresults to a value less than 1 or greater than 25 results in error response code 400 (Bad Request). If there are additional results to return, then the service returns a nextLink containing a skip token for pagination. In certain cases, the service might return fewer results than specified by maxresults (even 0 results) and also return a nextLink. Clients should not make any assumptions on the minimum number of results per page, and should enumerate all pages until the nextLink becomes null
    @constraint:Int {minValue: 1, maxValue: 25}
    int:Signed32 maxresults?;
};

# Represents the Queries record for the operation: purgeDeletedStorageAccount
public type PurgeDeletedStorageAccountQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Management policy for a certificate
public type CertificatePolicy record {
    # Properties of the X509 component of a certificate.
    @jsondata:Name {value: "x509_props"}
    X509CertificateProperties x509Props?;
    # The certificate attributes.
    CertificateAttributes attributes?;
    # The certificate id
    string id?;
    # Properties of the secret backing a certificate.
    @jsondata:Name {value: "secret_props"}
    SecretProperties secretProps?;
    # Actions that will be performed by Key Vault over the lifetime of a certificate
    @jsondata:Name {value: "lifetime_actions"}
    LifetimeAction[] lifetimeActions?;
    # Parameters for the issuer of the X509 component of a certificate.
    IssuerParameters issuer?;
    # Properties of the key backing a certificate.
    @jsondata:Name {value: "key_props"}
    KeyProperties keyProps?;
};

# Represents the Queries record for the operation: purgeDeletedSecret
public type PurgeDeletedSecretQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Details of the organization of the certificate issuer
public type OrganizationDetails record {
    # Id of the organization
    string id?;
    # Details of the organization administrator
    @jsondata:Name {value: "admin_details"}
    AdministratorDetails[] adminDetails?;
};

# Represents the Queries record for the operation: backupCertificate
public type BackupCertificateQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# A list of keys that have been deleted in this vault
public type DeletedKeyListResult record {
    # A response message containing a list of deleted keys in the vault along with a link to the next page of deleted keys
    DeletedKeyItem[] value?;
    # The URL to get the next set of deleted keys
    string nextLink?;
};

# The backup key result, containing the backup blob
public type BackupKeyResult record {
    # The backup blob containing the backed up key
    string value?;
};

# Represents the Queries record for the operation: recoverDeletedStorageAccount
public type RecoverDeletedStorageAccountQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: listStorageAccounts
public type ListStorageAccountsQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
    # Specifies the maximum number of results to return in a page. Setting maxresults to a value less than 1 or greater than 25 results in error response code 400 (Bad Request). If there are additional results to return, then the service returns a nextLink containing a skip token for pagination. In certain cases, the service might return fewer results than specified by maxresults (even 0 results) and also return a nextLink. Clients should not make any assumptions on the minimum number of results per page, and should enumerate all pages until the nextLink becomes null
    @constraint:Int {minValue: 1, maxValue: 25}
    int:Signed32 maxresults?;
};

# A SAS definition bundle consists of key vault SAS definition details plus its attributes
public type SasDefinitionBundle record {
    # The type of SAS token the SAS definition will create
    "account"|"service" sasType?;
    # The validity period of SAS tokens created according to the SAS definition
    string validityPeriod?;
    # The SAS definition token template signed with an arbitrary key.  Tokens created according to the SAS definition will have the same properties as the template
    string templateUri?;
    # The SAS definition attributes.
    SasDefinitionAttributes attributes?;
    # The SAS definition id
    string id?;
    # Storage account SAS definition secret id
    string sid?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# The storage account update parameters
public type StorageAccountUpdateParameters record {
    # The current active storage account key name
    string activeKeyName?;
    # The key regeneration time duration specified in ISO-8601 format
    string regenerationPeriod?;
    # The attributes of the storage account.
    StorageAccountAttributes attributes?;
    # whether keyvault should manage the storage account for the user
    boolean autoRegenerateKey?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# Represents the Queries record for the operation: sign
public type SignQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

@constraint:String {pattern: re `^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$`}
public type CertificateMergeParametersX5cItemsString string;

# The storage account create parameters
public type StorageAccountCreateParameters record {
    # Current active storage account key name
    string activeKeyName;
    # Storage account resource id
    string resourceId;
    # The key regeneration time duration specified in ISO-8601 format
    string regenerationPeriod?;
    # The attributes of the storage account.
    StorageAccountAttributes attributes?;
    # whether keyvault should manage the storage account for the user
    boolean autoRegenerateKey;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# Represents the Queries record for the operation: updateCertificateIssuer
public type UpdateCertificateIssuerQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:BearerTokenConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# Represents the Queries record for the operation: decrypt
public type DecryptQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The secret set parameters
public type SecretSetParameters record {
    # The secret management attributes.
    SecretAttributes attributes?;
    # The value of the secret
    string value;
    # Type of the secret value such as a password
    string contentType?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# Represents the Queries record for the operation: updateCertificateOperation
public type UpdateCertificateOperationQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The certificate create parameters
public type CertificateCreateParameters record {
    # The attributes of the certificate (optional).
    CertificateAttributes attributes?;
    # The management policy for the certificate.
    CertificatePolicy policy?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# A certificate bundle consists of a certificate (X509) plus its attributes
public type CertificateBundle record {
    # CER contents of x509 certificate
    @constraint:String {pattern: re `^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$`}
    string cer?;
    # Thumbprint of the certificate
    string x5t?;
    # The key id
    string kid?;
    # The certificate attributes.
    CertificateAttributes attributes?;
    # The certificate id
    string id?;
    # The content type of the secret
    string contentType?;
    # The secret id
    string sid?;
    # The management policy.
    CertificatePolicy policy?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# Represents the Queries record for the operation: getStorageAccount
public type GetStorageAccountQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: mergeCertificate
public type MergeCertificateQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# As of http://tools.ietf.org/html/draft-ietf-jose-json-web-key-18
public type JsonWebKey record {
    # RSA private exponent, or the D component of an EC private key
    string d?;
    # RSA public exponent
    string e?;
    # Elliptic curve name. For valid values, see JsonWebKeyCurveName
    "P-256"|"P-384"|"P-521"|"P-256K" crv?;
    # Key identifier
    string kid?;
    # HSM Token, used with 'Bring Your Own Key'
    @jsondata:Name {value: "key_hsm"}
    string keyHsm?;
    # Symmetric key
    string k?;
    # RSA private key parameter
    string dp?;
    # RSA private key parameter
    string dq?;
    # RSA modulus
    string n?;
    # RSA secret prime
    string p?;
    # JsonWebKey Key Type (kty), as defined in https://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-40
    "EC"|"EC-HSM"|"RSA"|"RSA-HSM"|"oct" kty?;
    # RSA secret prime, with p < q
    string q?;
    # Supported key operations.
    @jsondata:Name {value: "key_ops"}
    string[] keyOps?;
    # RSA private key parameter
    string qi?;
    # X component of an EC public key
    string x?;
    # Y component of an EC public key
    string y?;
};

# Represents the Queries record for the operation: purgeDeletedKey
public type PurgeDeletedKeyQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: setSecret
public type SetSecretQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: getCertificateOperation
public type GetCertificateOperationQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: deleteCertificateOperation
public type DeleteCertificateOperationQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The secret restore parameters
public type StorageRestoreParameters record {
    # The backup blob associated with a storage account
    string value;
};

# The key operations parameters
public type KeyOperationsParameters record {
    # algorithm identifier
    "RSA-OAEP"|"RSA-OAEP-256"|"RSA1_5" alg;
    # The data to be encrypted, decrypted, wrapped or unwrapped, as a base64url-encoded value.
    string value;
};

# Represents the Queries record for the operation: backupStorageAccount
public type BackupStorageAccountQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: setCertificateContacts
public type SetCertificateContactsQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The SAS definition update parameters
public type SasDefinitionUpdateParameters record {
    # The type of SAS token the SAS definition will create
    "account"|"service" sasType?;
    # The validity period of SAS tokens created according to the SAS definition
    string validityPeriod?;
    # The SAS definition token template signed with an arbitrary key.  Tokens created according to the SAS definition will have the same properties as the template
    string templateUri?;
    # The attributes of the SAS definition.
    SasDefinitionAttributes attributes?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# The deleted SAS definition list result
public type DeletedSasDefinitionListResult record {
    # A response message containing a list of the deleted SAS definitions in the vault along with a link to the next page of deleted sas definitions
    DeletedSasDefinitionItem[] value?;
    # The URL to get the next set of deleted SAS definitions
    string nextLink?;
};

# Represents the Queries record for the operation: backupKey
public type BackupKeyQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The key operations parameters
public type KeySignParameters record {
    # The signing/verification algorithm identifier. For more information on possible algorithm types, see JsonWebKeySignatureAlgorithm
    "PS256"|"PS384"|"PS512"|"RS256"|"RS384"|"RS512"|"RSNULL"|"ES256"|"ES384"|"ES512"|"ES256K" alg;
    # The digest to be signed, as a base64url-encoded value.
    string value;
};

# Represents the Queries record for the operation: deleteStorageAccount
public type DeleteStorageAccountQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The credentials to be used for the certificate issuer
public type IssuerCredentials record {
    # The user name/account name/account id
    @jsondata:Name {value: "account_id"}
    string accountId?;
    # The password/secret/account key
    string pwd?;
};

# Represents the Queries record for the operation: updateCertificatePolicy
public type UpdateCertificatePolicyQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# A DeletedKeyBundle consisting of a WebKey plus its Attributes and deletion info
public type DeletedKeyBundle record {
    *KeyBundle;
    # The url of the recovery object, used to identify and recover the deleted key.
    string recoveryId?;
    # The time when the key is scheduled to be purged, in UTC
    int scheduledPurgeDate?;
    # The time when the key was deleted, in UTC
    int deletedDate?;
};

# The storage account key regenerate parameters
public type StorageAccountRegenerateKeyParameters record {
    # The storage account key name
    string keyName;
};

# The deleted SAS definition item containing metadata about the deleted SAS definition
public type DeletedSasDefinitionItem record {
    *SasDefinitionItem;
    # The url of the recovery object, used to identify and recover the deleted SAS definition.
    string recoveryId?;
    # The time when the SAS definition is scheduled to be purged, in UTC
    int scheduledPurgeDate?;
    # The time when the SAS definition was deleted, in UTC
    int deletedDate?;
};

# The deleted certificate item containing metadata about the deleted certificate
public type DeletedCertificateItem record {
    *CertificateItem;
    # The url of the recovery object, used to identify and recover the deleted certificate.
    string recoveryId?;
    # The time when the certificate is scheduled to be purged, in UTC
    int scheduledPurgeDate?;
    # The time when the certificate was deleted, in UTC
    int deletedDate?;
};

# Represents the Queries record for the operation: updateStorageAccount
public type UpdateStorageAccountQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The deleted key item containing the deleted key metadata and information about deletion
public type DeletedKeyItem record {
    *KeyItem;
    # The url of the recovery object, used to identify and recover the deleted key.
    string recoveryId?;
    # The time when the key is scheduled to be purged, in UTC
    int scheduledPurgeDate?;
    # The time when the key was deleted, in UTC
    int deletedDate?;
};

# Represents the Queries record for the operation: listSecretVersions
public type ListSecretVersionsQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
    # Specifies the maximum number of results to return in a page. Setting maxresults to a value less than 1 or greater than 25 results in error response code 400 (Bad Request). If there are additional results to return, then the service returns a nextLink containing a skip token for pagination. In certain cases, the service might return fewer results than specified by maxresults (even 0 results) and also return a nextLink. Clients should not make any assumptions on the minimum number of results per page, and should enumerate all pages until the nextLink becomes null
    @constraint:Int {minValue: 1, maxValue: 25}
    int:Signed32 maxresults?;
};

# Action and its trigger that will be performed by Key Vault over the lifetime of a certificate
public type LifetimeAction record {
    # The action that will be executed.
    Action action?;
    # The condition that will execute the action.
    Trigger trigger?;
};

# A Deleted Certificate consisting of its previous id, attributes and its tags, as well as information on when it will be purged
public type DeletedCertificateBundle record {
    *CertificateBundle;
    # The url of the recovery object, used to identify and recover the deleted certificate.
    string recoveryId?;
    # The time when the certificate is scheduled to be purged, in UTC
    int scheduledPurgeDate?;
    # The time when the certificate was deleted, in UTC
    int deletedDate?;
};

# The secret item containing secret metadata
public type SecretItem record {
    # True if the secret's lifetime is managed by key vault. If this is a key backing a certificate, then managed will be true
    boolean managed?;
    # The secret management attributes.
    SecretAttributes attributes?;
    # Secret identifier
    string id?;
    # Type of the secret value such as a password
    string contentType?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# The certificate restore parameters
public type CertificateRestoreParameters record {
    # The backup blob associated with a certificate bundle
    string value;
};

# Represents the Queries record for the operation: getDeletedSasDefinition
public type GetDeletedSasDefinitionQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The key import parameters
public type KeyImportParameters record {
    # Whether to import as a hardware key (HSM) or software key
    @jsondata:Name {value: "Hsm"}
    boolean hsm?;
    # The key management attributes.
    KeyAttributes attributes?;
    # The Json web key
    JsonWebKey 'key;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# The certificate issuer update parameters
public type CertificateIssuerUpdateParameters record {
    # The issuer provider
    string provider?;
    # The credentials to be used for the issuer.
    IssuerCredentials credentials?;
    # Details of the organization as provided to the issuer.
    @jsondata:Name {value: "org_details"}
    OrganizationDetails orgDetails?;
    # Attributes of the issuer object.
    IssuerAttributes attributes?;
};

# Properties of the X509 component of a certificate
public type X509CertificateProperties record {
    # List of key usages
    @jsondata:Name {value: "key_usage"}
    ("digitalSignature"|"nonRepudiation"|"keyEncipherment"|"dataEncipherment"|"keyAgreement"|"keyCertSign"|"cRLSign"|"encipherOnly"|"decipherOnly")[] keyUsage?;
    # The duration that the certificate is valid in months
    @jsondata:Name {value: "validity_months"}
    int:Signed32 validityMonths?;
    # The subject name. Should be a valid X509 distinguished Name
    string subject?;
    # The subject alternative names.
    SubjectAlternativeNames sans?;
    # The enhanced key usage
    string[] ekus?;
};

# Represents the Queries record for the operation: recoverDeletedCertificate
public type RecoverDeletedCertificateQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The certificate update parameters
public type CertificateUpdateParameters record {
    # The attributes of the certificate (optional).
    CertificateAttributes attributes?;
    # The management policy for the certificate.
    CertificatePolicy policy?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# Represents the Queries record for the operation: restoreCertificate
public type RestoreCertificateQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# A list of certificates that have been deleted in this vault
public type DeletedCertificateListResult record {
    # A response message containing a list of deleted certificates in the vault along with a link to the next page of deleted certificates
    DeletedCertificateItem[] value?;
    # The URL to get the next set of deleted certificates
    string nextLink?;
};

# A secret consisting of a value, id and its attributes
public type SecretBundle record {
    # True if the secret's lifetime is managed by key vault. If this is a secret backing a certificate, then managed will be true
    boolean managed?;
    # If this is a secret backing a KV certificate, then this field specifies the corresponding key backing the KV certificate
    string kid?;
    # The secret management attributes.
    SecretAttributes attributes?;
    # The secret id
    string id?;
    # The secret value
    string value?;
    # The content type of the secret
    string contentType?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# Represents the Queries record for the operation: unwrapKey
public type UnwrapKeyQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# A KeyBundle consisting of a WebKey plus its attributes
public type KeyBundle record {
    # True if the key's lifetime is managed by key vault. If this is a key backing a certificate, then managed will be true
    boolean managed?;
    # The key management attributes.
    KeyAttributes attributes?;
    # The Json web key.
    JsonWebKey 'key?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# Represents the Queries record for the operation: wrapKey
public type WrapKeyQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: listSasDefinitions
public type ListSasDefinitionsQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
    # Specifies the maximum number of results to return in a page. Setting maxresults to a value less than 1 or greater than 25 results in error response code 400 (Bad Request). If there are additional results to return, then the service returns a nextLink containing a skip token for pagination. In certain cases, the service might return fewer results than specified by maxresults (even 0 results) and also return a nextLink. Clients should not make any assumptions on the minimum number of results per page, and should enumerate all pages until the nextLink becomes null
    @constraint:Int {minValue: 1, maxValue: 25}
    int:Signed32 maxresults?;
};

# The storage accounts list result
public type StorageListResult record {
    # A response message containing a list of storage accounts in the key vault along with a link to the next page of storage accounts
    StorageAccountItem[] value?;
    # The URL to get the next set of storage accounts
    string nextLink?;
};

# Represents the Queries record for the operation: importKey
public type ImportKeyQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: listCertificateVersions
public type ListCertificateVersionsQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
    # Specifies the maximum number of results to return in a page. Setting maxresults to a value less than 1 or greater than 25 results in error response code 400 (Bad Request). If there are additional results to return, then the service returns a nextLink containing a skip token for pagination. In certain cases, the service might return fewer results than specified by maxresults (even 0 results) and also return a nextLink. Clients should not make any assumptions on the minimum number of results per page, and should enumerate all pages until the nextLink becomes null
    @constraint:Int {minValue: 1, maxValue: 25}
    int:Signed32 maxresults?;
};

# The attributes of a key managed by the key vault service
public type KeyAttributes record {
    *Attributes;
    # Reflects the deletion recovery level currently in effect for keys in the current vault. If it contains 'Purgeable' the key can be permanently deleted by a privileged user; otherwise, only the system can purge the key, at the end of the retention interval.
    "Purgeable"|"Recoverable+Purgeable"|"Recoverable"|"Recoverable+ProtectedSubscription" recoveryLevel?;
};

# The key list result
public type KeyListResult record {
    # A response message containing a list of keys in the key vault along with a link to the next page of keys
    KeyItem[] value?;
    # The URL to get the next set of keys
    string nextLink?;
};

# Parameters for the issuer of the X509 component of a certificate
public type IssuerParameters record {
    # Indicates if the certificates generated under this policy should be published to certificate transparency logs
    @jsondata:Name {value: "cert_transparency"}
    boolean certTransparency?;
    # Name of the referenced issuer object or reserved names; for example, 'Self' or 'Unknown'
    string name?;
    # Certificate type as supported by the provider (optional); for example 'OV-SSL', 'EV-SSL'
    string cty?;
};

# The certificate merge parameters
public type CertificateMergeParameters record {
    # The certificate or the certificate chain to merge
    CertificateMergeParametersX5cItemsString[] x5c;
    # The attributes of the certificate (optional).
    CertificateAttributes attributes?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# The subject alternate names of a X509 object
public type SubjectAlternativeNames record {
    # Email addresses
    string[] emails?;
    # Domain names
    @jsondata:Name {value: "dns_names"}
    string[] dnsNames?;
    # User principal names
    string[] upns?;
};

# Represents the Queries record for the operation: updateSasDefinition
public type UpdateSasDefinitionQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The key item containing key metadata
public type KeyItem record {
    # True if the key's lifetime is managed by key vault. If this is a key backing a certificate, then managed will be true
    boolean managed?;
    # Key identifier
    string kid?;
    # The key management attributes.
    KeyAttributes attributes?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# The deleted secret item containing metadata about the deleted secret
public type DeletedSecretItem record {
    *SecretItem;
    # The url of the recovery object, used to identify and recover the deleted secret.
    string recoveryId?;
    # The time when the secret is scheduled to be purged, in UTC
    int scheduledPurgeDate?;
    # The time when the secret was deleted, in UTC
    int deletedDate?;
};

# A certificate operation is returned in case of asynchronous requests
public type CertificateOperation record {
    # The certificate signing request (CSR) that is being used in the certificate operation
    @constraint:String {pattern: re `^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$`}
    string csr?;
    # Indicates if cancellation was requested on the certificate operation
    @jsondata:Name {value: "cancellation_requested"}
    boolean cancellationRequested?;
    # The certificate id
    string id?;
    # Error encountered, if any, during the certificate operation.
    Error 'error?;
    # The status details of the certificate operation
    @jsondata:Name {value: "status_details"}
    string statusDetails?;
    # Identifier for the certificate operation
    @jsondata:Name {value: "request_id"}
    string requestId?;
    # Parameters for the issuer of the X509 component of a certificate.
    IssuerParameters issuer?;
    # Status of the certificate operation
    string status?;
    # Location which contains the result of the certificate operation
    string target?;
};

# The deleted secret list result
public type DeletedSecretListResult record {
    # A response message containing a list of the deleted secrets in the vault along with a link to the next page of deleted secrets
    DeletedSecretItem[] value?;
    # The URL to get the next set of deleted secrets
    string nextLink?;
};

# Represents the Queries record for the operation: updateCertificate
public type UpdateCertificateQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: listDeletedCertificates
public type ListDeletedCertificatesQueries record {
    # Specifies whether to include certificates which are not completely provisioned
    boolean includePending?;
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
    # Specifies the maximum number of results to return in a page. Setting maxresults to a value less than 1 or greater than 25 results in error response code 400 (Bad Request). If there are additional results to return, then the service returns a nextLink containing a skip token for pagination. In certain cases, the service might return fewer results than specified by maxresults (even 0 results) and also return a nextLink. Clients should not make any assumptions on the minimum number of results per page, and should enumerate all pages until the nextLink becomes null
    @constraint:Int {minValue: 1, maxValue: 25}
    int:Signed32 maxresults?;
};

# The key restore parameters
public type KeyRestoreParameters record {
    # The backup blob associated with a key bundle
    string value;
};

# Properties of the key backing a certificate
public type SecretProperties record {
    # The media type (MIME type)
    string contentType?;
};

# The key verify result
public type KeyVerifyResult record {
    # True if the signature is verified, otherwise false
    boolean value?;
};

# The contacts for the vault certificates
public type Contacts record {
    # Identifier for the contacts collection
    string id?;
    # The contact list for the vault certificates
    Contact[] contacts?;
};

# Represents the Queries record for the operation: regenerateStorageAccountKey
public type RegenerateStorageAccountKeyQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: updateKey
public type UpdateKeyQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: restoreKey
public type RestoreKeyQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: getDeletedCertificate
public type GetDeletedCertificateQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: getCertificatePolicy
public type GetCertificatePolicyQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: listDeletedSasDefinitions
public type ListDeletedSasDefinitionsQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
    # Specifies the maximum number of results to return in a page. Setting maxresults to a value less than 1 or greater than 25 results in error response code 400 (Bad Request). If there are additional results to return, then the service returns a nextLink containing a skip token for pagination. In certain cases, the service might return fewer results than specified by maxresults (even 0 results) and also return a nextLink. Clients should not make any assumptions on the minimum number of results per page, and should enumerate all pages until the nextLink becomes null
    @constraint:Int {minValue: 1, maxValue: 25}
    int:Signed32 maxresults?;
};

# The key verify parameters
public type KeyVerifyParameters record {
    # The digest used for signing
    string digest;
    # The signing/verification algorithm. For more information on possible algorithm types, see JsonWebKeySignatureAlgorithm
    "PS256"|"PS384"|"PS512"|"RS256"|"RS384"|"RS512"|"RSNULL"|"ES256"|"ES384"|"ES512"|"ES256K" alg;
    # The signature to be verified
    string value;
};

# Represents the Queries record for the operation: deleteSecret
public type DeleteSecretQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: restoreStorageAccount
public type RestoreStorageAccountQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: recoverDeletedSecret
public type RecoverDeletedSecretQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: verify
public type VerifyQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The object attributes managed by the KeyVault service
public type Attributes record {
    # Not before date in UTC
    int nbf?;
    # Creation time in UTC
    int created?;
    # Expiry date in UTC
    int exp?;
    # Last updated time in UTC
    int updated?;
    # Determines whether the object is enabled
    boolean enabled?;
};

# Represents the Queries record for the operation: getSecret
public type GetSecretQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The attributes of an issuer managed by the Key Vault service
public type IssuerAttributes record {
    # Creation time in UTC
    int created?;
    # Last updated time in UTC
    int updated?;
    # Determines whether the issuer is enabled
    boolean enabled?;
};

# The certificate import parameters
public type CertificateImportParameters record {
    # The attributes of the certificate (optional).
    CertificateAttributes attributes?;
    # If the private key in base64EncodedCertificate is encrypted, the password used for encryption
    string pwd?;
    # Base64 encoded representation of the certificate object to import. This certificate needs to contain the private key
    string value;
    # The management policy for the certificate.
    CertificatePolicy policy?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# Represents the Queries record for the operation: getSasDefinition
public type GetSasDefinitionQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: recoverDeletedSasDefinition
public type RecoverDeletedSasDefinitionQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The secret restore parameters
public type SecretRestoreParameters record {
    # The backup blob associated with a secret bundle
    string value;
};

# The storage account item containing storage account metadata
public type StorageAccountItem record {
    # Storage account resource Id
    string resourceId?;
    # The storage account management attributes.
    StorageAccountAttributes attributes?;
    # Storage identifier
    string id?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# A condition to be satisfied for an action to be executed
public type Trigger record {
    # Percentage of lifetime at which to trigger. Value should be between 1 and 99
    @jsondata:Name {value: "lifetime_percentage"}
    int:Signed32 lifetimePercentage?;
    # Days before expiry to attempt renewal. Value should be between 1 and validity_in_months multiplied by 27. If validity_in_months is 36, then value should be between 1 and 972 (36 * 27)
    @jsondata:Name {value: "days_before_expiry"}
    int:Signed32 daysBeforeExpiry?;
};

# Represents the Queries record for the operation: setStorageAccount
public type SetStorageAccountQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: getKey
public type GetKeyQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: getDeletedKey
public type GetDeletedKeyQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: listCertificateIssuers
public type ListCertificateIssuersQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
    # Specifies the maximum number of results to return in a page. Setting maxresults to a value less than 1 or greater than 25 results in error response code 400 (Bad Request). If there are additional results to return, then the service returns a nextLink containing a skip token for pagination. In certain cases, the service might return fewer results than specified by maxresults (even 0 results) and also return a nextLink. Clients should not make any assumptions on the minimum number of results per page, and should enumerate all pages until the nextLink becomes null
    @constraint:Int {minValue: 1, maxValue: 25}
    int:Signed32 maxresults?;
};

# Represents the Queries record for the operation: getCertificateIssuer
public type GetCertificateIssuerQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The storage account management attributes
public type StorageAccountAttributes record {
    # Creation time in UTC
    int created?;
    # Reflects the deletion recovery level currently in effect for storage accounts in the current vault. If it contains 'Purgeable' the storage account can be permanently deleted by a privileged user; otherwise, only the system can purge the storage account, at the end of the retention interval
    "Purgeable"|"Recoverable+Purgeable"|"Recoverable"|"Recoverable+ProtectedSubscription" recoveryLevel?;
    # Last updated time in UTC
    int updated?;
    # the enabled state of the object
    boolean enabled?;
};

# The backup storage result, containing the backup blob
public type BackupStorageResult record {
    # The backup blob containing the backed up storage account
    string value?;
};

# The key operation result
public type KeyOperationResult record {
    # Key identifier
    string kid?;
    # The result of the key operation, as a base64url-encoded value.
    string value?;
};

# The key update parameters
public type KeyUpdateParameters record {
    # Json web key operations. For more information on possible key operations, see JsonWebKeyOperation
    @jsondata:Name {value: "key_ops"}
    ("encrypt"|"decrypt"|"sign"|"verify"|"wrapKey"|"unwrapKey")[] keyOps?;
    # The attributes of the key to update.
    KeyAttributes attributes?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# A Deleted Secret consisting of its previous id, attributes and its tags, as well as information on when it will be purged
public type DeletedSecretBundle record {
    *SecretBundle;
    # The url of the recovery object, used to identify and recover the deleted secret.
    string recoveryId?;
    # The time when the secret is scheduled to be purged, in UTC
    int scheduledPurgeDate?;
    # The time when the secret was deleted, in UTC
    int deletedDate?;
};

# Represents the Queries record for the operation: listKeyVersions
public type ListKeyVersionsQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
    # Specifies the maximum number of results to return in a page. Setting maxresults to a value less than 1 or greater than 25 results in error response code 400 (Bad Request). If there are additional results to return, then the service returns a nextLink containing a skip token for pagination. In certain cases, the service might return fewer results than specified by maxresults (even 0 results) and also return a nextLink. Clients should not make any assumptions on the minimum number of results per page, and should enumerate all pages until the nextLink becomes null
    @constraint:Int {minValue: 1, maxValue: 25}
    int:Signed32 maxresults?;
};

# Represents the Queries record for the operation: deleteCertificateContacts
public type DeleteCertificateContactsQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: deleteKey
public type DeleteKeyQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: deleteCertificate
public type DeleteCertificateQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The backup certificate result, containing the backup blob
public type BackupCertificateResult record {
    # The backup blob containing the backed up certificate
    string value?;
};

# Represents the Queries record for the operation: getDeletedStorageAccount
public type GetDeletedStorageAccountQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: deleteSasDefinition
public type DeleteSasDefinitionQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The backup secret result, containing the backup blob
public type BackupSecretResult record {
    # The backup blob containing the backed up secret
    string value?;
};

# Represents the Queries record for the operation: listDeletedStorageAccounts
public type ListDeletedStorageAccountsQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
    # Specifies the maximum number of results to return in a page. Setting maxresults to a value less than 1 or greater than 25 results in error response code 400 (Bad Request). If there are additional results to return, then the service returns a nextLink containing a skip token for pagination. In certain cases, the service might return fewer results than specified by maxresults (even 0 results) and also return a nextLink. Clients should not make any assumptions on the minimum number of results per page, and should enumerate all pages until the nextLink becomes null
    @constraint:Int {minValue: 1, maxValue: 25}
    int:Signed32 maxresults?;
};

# A deleted SAS definition bundle consisting of its previous id, attributes and its tags, as well as information on when it will be purged
public type DeletedSasDefinitionBundle record {
    *SasDefinitionBundle;
    # The url of the recovery object, used to identify and recover the deleted SAS definition.
    string recoveryId?;
    # The time when the SAS definition is scheduled to be purged, in UTC
    int scheduledPurgeDate?;
    # The time when the SAS definition was deleted, in UTC
    int deletedDate?;
};

# Represents the Queries record for the operation: createKey
public type CreateKeyQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: getDeletedSecret
public type GetDeletedSecretQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: purgeDeletedCertificate
public type PurgeDeletedCertificateQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: recoverDeletedKey
public type RecoverDeletedKeyQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: restoreSecret
public type RestoreSecretQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The action that will be executed
public type Action record {
    # The type of the action
    @jsondata:Name {value: "action_type"}
    "EmailContacts"|"AutoRenew" actionType?;
};

# The SAS definition management attributes
public type SasDefinitionAttributes record {
    # Creation time in UTC
    int created?;
    # Reflects the deletion recovery level currently in effect for SAS definitions in the current vault. If it contains 'Purgeable' the SAS definition can be permanently deleted by a privileged user; otherwise, only the system can purge the SAS definition, at the end of the retention interval
    "Purgeable"|"Recoverable+Purgeable"|"Recoverable"|"Recoverable+ProtectedSubscription" recoveryLevel?;
    # Last updated time in UTC
    int updated?;
    # the enabled state of the object
    boolean enabled?;
};

# Represents the Queries record for the operation: setCertificateIssuer
public type SetCertificateIssuerQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: listCertificates
public type ListCertificatesQueries record {
    # Specifies whether to include certificates which are not completely provisioned
    boolean includePending?;
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
    # Specifies the maximum number of results to return in a page. Setting maxresults to a value less than 1 or greater than 25 results in error response code 400 (Bad Request). If there are additional results to return, then the service returns a nextLink containing a skip token for pagination. In certain cases, the service might return fewer results than specified by maxresults (even 0 results) and also return a nextLink. Clients should not make any assumptions on the minimum number of results per page, and should enumerate all pages until the nextLink becomes null
    @constraint:Int {minValue: 1, maxValue: 25}
    int:Signed32 maxresults?;
};

# A Storage account bundle consists of key vault storage account details plus its attributes
public type StorageBundle record {
    # The current active storage account key name
    string activeKeyName?;
    # The storage account resource id
    string resourceId?;
    # The key regeneration time duration specified in ISO-8601 format
    string regenerationPeriod?;
    # The storage account attributes.
    StorageAccountAttributes attributes?;
    # The storage account id
    string id?;
    # whether keyvault should manage the storage account for the user
    boolean autoRegenerateKey?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# The SAS definition create parameters
public type SasDefinitionCreateParameters record {
    # The type of SAS token the SAS definition will create
    "account"|"service" sasType;
    # The validity period of SAS tokens created according to the SAS definition
    string validityPeriod;
    # The SAS definition token template signed with an arbitrary key.  Tokens created according to the SAS definition will have the same properties as the template
    string templateUri;
    # The attributes of the SAS definition.
    SasDefinitionAttributes attributes?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# Represents the Queries record for the operation: createCertificate
public type CreateCertificateQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The secret update parameters
public type SecretUpdateParameters record {
    # The secret management attributes.
    SecretAttributes attributes?;
    # Type of the secret value such as a password
    string contentType?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# The key create parameters
public type KeyCreateParameters record {
    # The type of key to create. For valid values, see JsonWebKeyType
    "EC"|"EC-HSM"|"RSA"|"RSA-HSM"|"oct" kty;
    # Elliptic curve name. For valid values, see JsonWebKeyCurveName
    "P-256"|"P-384"|"P-521"|"P-256K" crv?;
    # JSON web key operations permitted on the key.
    @jsondata:Name {value: "key_ops"}
    ("encrypt"|"decrypt"|"sign"|"verify"|"wrapKey"|"unwrapKey")[] keyOps?;
    # The attributes of the key to create.
    KeyAttributes attributes?;
    # The key size in bits. For example: 2048, 3072, or 4096 for RSA
    @jsondata:Name {value: "key_size"}
    int:Signed32 keySize?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# The storage account SAS definition list result
public type SasDefinitionListResult record {
    # A response message containing a list of SAS definitions along with a link to the next page of SAS definitions
    SasDefinitionItem[] value?;
    # The URL to get the next set of SAS definitions
    string nextLink?;
};

# The deleted storage account item containing metadata about the deleted storage account
public type DeletedStorageAccountItem record {
    *StorageAccountItem;
    # The url of the recovery object, used to identify and recover the deleted storage account.
    string recoveryId?;
    # The time when the storage account is scheduled to be purged, in UTC
    int scheduledPurgeDate?;
    # The time when the storage account was deleted, in UTC
    int deletedDate?;
};

# Represents the Queries record for the operation: updateSecret
public type UpdateSecretQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The certificate issuer item containing certificate issuer metadata
public type CertificateIssuerItem record {
    # The issuer provider
    string provider?;
    # Certificate Identifier
    string id?;
};

# Represents the Queries record for the operation: getCertificate
public type GetCertificateQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: listDeletedKeys
public type ListDeletedKeysQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
    # Specifies the maximum number of results to return in a page. Setting maxresults to a value less than 1 or greater than 25 results in error response code 400 (Bad Request). If there are additional results to return, then the service returns a nextLink containing a skip token for pagination. In certain cases, the service might return fewer results than specified by maxresults (even 0 results) and also return a nextLink. Clients should not make any assumptions on the minimum number of results per page, and should enumerate all pages until the nextLink becomes null
    @constraint:Int {minValue: 1, maxValue: 25}
    int:Signed32 maxresults?;
};

# Represents the Queries record for the operation: importCertificate
public type ImportCertificateQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The SAS definition item containing storage SAS definition metadata
public type SasDefinitionItem record {
    # The SAS definition management attributes.
    SasDefinitionAttributes attributes?;
    # The storage SAS identifier
    string id?;
    # The storage account SAS definition secret id
    string sid?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# Properties of the key pair backing a certificate
public type KeyProperties record {
    # The type of key pair to be used for the certificate
    "EC"|"EC-HSM"|"RSA"|"RSA-HSM"|"oct" kty?;
    # Indicates if the private key can be exported
    boolean exportable?;
    # Indicates if the same key pair will be used on certificate renewal
    @jsondata:Name {value: "reuse_key"}
    boolean reuseKey?;
    # Elliptic curve name. For valid values, see JsonWebKeyCurveName
    "P-256"|"P-384"|"P-521"|"P-256K" crv?;
    # The key size in bits. For example: 2048, 3072, or 4096 for RSA
    @jsondata:Name {value: "key_size"}
    int:Signed32 keySize?;
};

# Represents the Queries record for the operation: getCertificateContacts
public type GetCertificateContactsQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The certificate management attributes
public type CertificateAttributes record {
    *Attributes;
    # Reflects the deletion recovery level currently in effect for certificates in the current vault. If it contains 'Purgeable', the certificate can be permanently deleted by a privileged user; otherwise, only the system can purge the certificate, at the end of the retention interval.
    "Purgeable"|"Recoverable+Purgeable"|"Recoverable"|"Recoverable+ProtectedSubscription" recoveryLevel?;
};

# The certificate list result
public type CertificateListResult record {
    # A response message containing a list of certificates in the key vault along with a link to the next page of certificates
    CertificateItem[] value?;
    # The URL to get the next set of certificates
    string nextLink?;
};

# Represents the Queries record for the operation: deleteCertificateIssuer
public type DeleteCertificateIssuerQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# The key vault server error
public type Error record {
    # The error code
    string code?;
    # The inner error, containing a more specific error code, if any.
    Error innererror?;
    # The error message
    string message?;
};

# The certificate issuer set parameters
public type CertificateIssuerSetParameters record {
    # The issuer provider
    string provider;
    # The credentials to be used for the issuer.
    IssuerCredentials credentials?;
    # Details of the organization as provided to the issuer.
    @jsondata:Name {value: "org_details"}
    OrganizationDetails orgDetails?;
    # Attributes of the issuer object.
    IssuerAttributes attributes?;
};

# The certificate operation update parameters
public type CertificateOperationUpdateParameter record {
    # Indicates if cancellation was requested on the certificate operation
    @jsondata:Name {value: "cancellation_requested"}
    boolean cancellationRequested;
};

# A deleted storage account bundle consisting of its previous id, attributes and its tags, as well as information on when it will be purged
public type DeletedStorageBundle record {
    *StorageBundle;
    # The url of the recovery object, used to identify and recover the deleted storage account.
    string recoveryId?;
    # The time when the storage account is scheduled to be purged, in UTC
    int scheduledPurgeDate?;
    # The time when the storage account was deleted, in UTC
    int deletedDate?;
};

# The contact information for the vault certificates
public type Contact record {
    # Phone number
    string phone?;
    # Name of the contact.
    string name?;
    # Email address
    string email?;
};

# The issuer for Key Vault certificate
public type IssuerBundle record {
    # The issuer provider
    string provider?;
    # The credentials to be used for the issuer.
    IssuerCredentials credentials?;
    # Details of the organization as provided to the issuer.
    @jsondata:Name {value: "org_details"}
    OrganizationDetails orgDetails?;
    # Attributes of the issuer object.
    IssuerAttributes attributes?;
    # Identifier for the issuer object
    string id?;
};

# Represents the Queries record for the operation: setSasDefinition
public type SetSasDefinitionQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: encrypt
public type EncryptQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Represents the Queries record for the operation: listDeletedSecrets
public type ListDeletedSecretsQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
    # Specifies the maximum number of results to return in a page. Setting maxresults to a value less than 1 or greater than 25 results in error response code 400 (Bad Request). If there are additional results to return, then the service returns a nextLink containing a skip token for pagination. In certain cases, the service might return fewer results than specified by maxresults (even 0 results) and also return a nextLink. Clients should not make any assumptions on the minimum number of results per page, and should enumerate all pages until the nextLink becomes null
    @constraint:Int {minValue: 1, maxValue: 25}
    int:Signed32 maxresults?;
};

# The certificate item containing certificate metadata
public type CertificateItem record {
    # Thumbprint of the certificate
    string x5t?;
    # The certificate management attributes.
    CertificateAttributes attributes?;
    # Certificate identifier
    string id?;
    # Application specific metadata in the form of key-value pairs
    record {|string...;|} tags?;
};

# The secret management attributes
public type SecretAttributes record {
    *Attributes;
    # Reflects the deletion recovery level currently in effect for secrets in the current vault. If it contains 'Purgeable', the secret can be permanently deleted by a privileged user; otherwise, only the system can purge the secret, at the end of the retention interval.
    "Purgeable"|"Recoverable+Purgeable"|"Recoverable"|"Recoverable+ProtectedSubscription" recoveryLevel?;
};

# The secret list result
public type SecretListResult record {
    # A response message containing a list of secrets in the key vault along with a link to the next page of secrets
    SecretItem[] value?;
    # The URL to get the next set of secrets
    string nextLink?;
};

# The certificate issuer list result
public type CertificateIssuerListResult record {
    # A response message containing a list of certificate issuers in the key vault along with a link to the next page of certificate issuers
    CertificateIssuerItem[] value?;
    # The URL to get the next set of certificate issuers
    string nextLink?;
};

# Represents the Queries record for the operation: listSecrets
public type ListSecretsQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
    # Specifies the maximum number of results to return in a page. Setting maxresults to a value less than 1 or greater than 25 results in error response code 400 (Bad Request). If there are additional results to return, then the service returns a nextLink containing a skip token for pagination. In certain cases, the service might return fewer results than specified by maxresults (even 0 results) and also return a nextLink. Clients should not make any assumptions on the minimum number of results per page, and should enumerate all pages until the nextLink becomes null
    @constraint:Int {minValue: 1, maxValue: 25}
    int:Signed32 maxresults?;
};

# Represents the Queries record for the operation: backupSecret
public type BackupSecretQueries record {
    # Client API version
    @http:Query {name: "api-version"}
    string apiVersion;
};

# Details of the organization administrator of the certificate issuer
public type AdministratorDetails record {
    # Phone number
    string phone?;
    # Last name of the administrator.
    @jsondata:Name {value: "last_name"}
    string lastName?;
    # First name
    @jsondata:Name {value: "first_name"}
    string firstName?;
    # Email address
    string email?;
};

# The deleted storage account list result
public type DeletedStorageListResult record {
    # A response message containing a list of the deleted storage accounts in the vault along with a link to the next page of deleted storage accounts
    DeletedStorageAccountItem[] value?;
    # The URL to get the next set of deleted storage accounts
    string nextLink?;
};
